<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoadmapSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('roadmap')->insert([
            ['id' => 38, 'acao' => 'Entregue a primeira versão do software do Fundo Social, para testes de aderência em relação à rotina do setor.',                                                                         'status' => 'entregue_recentemente', 'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 40, 'acao' => 'Adesão à rede Gov BR, posibilitando integração de sistemas municipais com o governo federal.',                                                                                           'status' => 'entregue_recentemente', 'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 41, 'acao' => 'Integração da plataforma e-SUS com a rede Gov BR, possibilitando acesso com login único.',                                                                                               'status' => 'entregue_recentemente', 'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 42, 'acao' => 'Desenvolvimento de site "Estratégia Digital", dando transparência e prestando contas das ações vinculadas ao uso de tecnologia no município.',                                           'status' => 'em_andamento',          'eixo_id' => 5, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 43, 'acao' => 'Disponibilização de agendamento de consultas através do aplicativo "Meu SUS Digital".',                                                                                                 'status' => 'em_andamento',          'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 44, 'acao' => 'Readequação site Empreenda Caraguatatuba para nova edição do evento',                                                                                                                    'status' => 'em_andamento',          'eixo_id' => 3, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 46, 'acao' => 'Desenvolvimento de Software para a Secretaria dos Direitos da Pessoa com Deficiência e Idoso, com o intuito de modernizar e amparar a operação da Secretaria',                          'status' => 'explorando',            'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 47, 'acao' => 'Elaboração LOA e PPA 2026',                                                                                                                                                             'status' => 'entregue_recentemente', 'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 48, 'acao' => 'Decreto 2353 - Altera Grupo de Trabalho LGPD',                                                                                                                                          'status' => 'entregue_recentemente', 'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 49, 'acao' => 'Estruturação interna do Grupo de Trabalho - LGPD',                                                                                                                                      'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 50, 'acao' => 'Processo licitatório para renovação/complementação do parque de máquinas da Prefeitura',                                                                                                 'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 51, 'acao' => 'Processo licitatório para implantação do CSI - Centro de Segurança e Inteligência',                                                                                                     'status' => 'em_andamento',          'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 52, 'acao' => 'Processo licitatório para ampliação e melhorias da Central 156, incluindo os serviços de 199 e 153',                                                                                    'status' => 'em_andamento',          'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 53, 'acao' => 'Elaboração da política de dados abertos',                                                                                                                                               'status' => 'em_andamento',          'eixo_id' => 5, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 54, 'acao' => 'Regulamentação da Assinatura Digital',                                                                                                                                                  'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 55, 'acao' => 'Regulamentação de Processos Digitais',                                                                                                                                                  'status' => 'em_andamento',          'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 56, 'acao' => 'Implantação do Digitaliza Caraguá, criando locais públicos para acesso à internet em ambiente acadêmico',                                                                                'status' => 'em_andamento',          'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 57, 'acao' => 'Adequação ao PROCEL - Programa Nacional de Conservação de Energia Elétrica',                                                                                                            'status' => 'em_andamento',          'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 58, 'acao' => 'Implantação de Software no Conselho Tutelar',                                                                                                                                           'status' => 'em_andamento',          'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 59, 'acao' => 'Implantação de Gestão à Vista, com dashboards de informações da operação da Secretaria de Tecnologia',                                                                                  'status' => 'em_andamento',          'eixo_id' => 3, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 60, 'acao' => 'Implantação do Conecta, plataforma de comunicação corporativa',                                                                                                                         'status' => 'entregue_recentemente', 'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 61, 'acao' => 'Implantação do Resolve STII, facilitando o acesso das outras Secretarias à STII e proporcionando melhor visão do fluxo de demandas',                                                    'status' => 'entregue_recentemente', 'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 62, 'acao' => 'Disponibilização do Cadastro de Fornecedores Online, atendendo demanda do TCE e democratizando o acesso dos fornecedores',                                                               'status' => 'em_andamento',          'eixo_id' => 5, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 63, 'acao' => 'Automações de alertas de incidentes no ambiente de T.I, possibilitando monitoramento ativo e resposta ágil',                                                                            'status' => 'explorando',            'eixo_id' => 3, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 64, 'acao' => 'Elaboração de projeto de monitoramente interno das unidades da Secretaria de Educação',                                                                                                  'status' => 'em_andamento',          'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 65, 'acao' => 'Estruturação do evento Ação Cidadania',                                                                                                                                                 'status' => 'em_andamento',          'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 66, 'acao' => 'Melhorias nos fluxos internos da STII, através da cultura de dados',                                                                                                                    'status' => 'entregue_recentemente', 'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 67, 'acao' => 'Regulamentação da Lei do Governo Digital',                                                                                                                                              'status' => 'entregue_recentemente', 'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 68, 'acao' => 'Criação de Data Lake municipal, possibilitando centralização e integração dos dados, além do suporte à tomada de decisão',                                                               'status' => 'explorando',            'eixo_id' => 3, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 69, 'acao' => 'Regulamentação da LGPD',                                                                                                                                                                'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 70, 'acao' => 'Desenvolvimento de Software para publicação do Diário Oficial, facilitando o acesso da população à informação',                                                                          'status' => 'entregue_recentemente', 'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 71, 'acao' => 'Desenvolvimento de Software para votação do Caraguá Agosto 2025, facilitando e dando transparência ao processo de votação',                                                              'status' => 'entregue_recentemente', 'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 72, 'acao' => 'Autenticação única e integrada em todos os serviços digitais',                                                                                                                          'status' => 'em_andamento',          'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 73, 'acao' => 'Unificação de cadastros de cidadãos e empresas',                                                                                                                                        'status' => 'em_andamento',          'eixo_id' => 2, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 74, 'acao' => 'Campanhas educativas e conscientização para usuários finais',                                                                                                                           'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 75, 'acao' => 'Autenticação multifator (MFA) em sistemas críticos',                                                                                                                                    'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 76, 'acao' => 'Políticas de cibersegurança alinhadas à ISO/IEC 22300, 27000, 31000 e 38000.',                                                                                                          'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 77, 'acao' => 'Criação de ambiente Sandbox para homologação e validação das soluções tecnológicas',                                                                                                     'status' => 'explorando',            'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 78, 'acao' => 'Política de redundância e backup inteligente',                                                                                                                                          'status' => 'em_andamento',          'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 79, 'acao' => 'Integração da ouvidoria digital ao portal único',                                                                                                                                       'status' => 'explorando',            'eixo_id' => 1, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 80, 'acao' => 'Evento #ElasTech, promovendo inclusão das alunas da rede municipal ao mercado de tecnologia',                                                                                           'status' => 'entregue_recentemente', 'eixo_id' => 3, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 81, 'acao' => 'Gestão centralizada de ativos de TI',                                                                                                                                                   'status' => 'entregue_recentemente', 'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 82, 'acao' => 'Matriz de riscos de TI',                                                                                                                                                                'status' => 'entregue_recentemente', 'eixo_id' => 4, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 83, 'acao' => 'Relatórios públicos de resultados',                                                                                                                                                     'status' => 'explorando',            'eixo_id' => 5, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => 84, 'acao' => 'Digitalização dos processos de aditamentos de viagens, promovendo economia nos trâmites das Secretarias',                                                                                'status' => 'explorando',            'eixo_id' => 6, 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
        ]);
    }
}
